sudo: false

language: node_js
node_js: node

cache:
  directories:
    - test/elm-stuff/build-artifacts
    - sysconfcpus

before_install:
  - | # epic build time improvement - see https://github.com/elm-lang/elm-compiler/issues/1473#issuecomment-245704142
    if [ ! -d sysconfcpus/bin ];
    then
      git clone https://github.com/obmarg/libsysconfcpus.git;
      cd libsysconfcpus;
      ./configure --prefix=$TRAVIS_BUILD_DIR/sysconfcpus;
      make && make install;
      cd ..;
    fi

install:
  - npm install
  - mv $TRAVIS_BUILD_DIR/node_modules/.bin/elm-make $TRAVIS_BUILD_DIR/node_modules/.bin/elm-make-old
  - printf "#\041/bin/bash\n\necho \"Running elm-make with sysconfcpus -n 2\"\n\n$TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 elm-make-old \"\$@\"" > $TRAVIS_BUILD_DIR/node_modules/.bin/elm-make
  - chmod +x $TRAVIS_BUILD_DIR/node_modules/.bin/elm-make

script:
  - npm test